# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66628fc68c4750f02e538dd8eebe9364b1c84762860d1d74dd70f51bd59a251fee7b2d3dfe85ddf3343bc5450d8941c3192bcb9eda22e2a625824e97107afc11

test:
  secret_key_base: b90b47e00b84c12efcf5762cbc6a0b1b2ccecc39937528e0c796b3dd25650b4db95d50bf7432fbbcd2beb9c2efd2f20f1be4e02e3492d4d33a024adc00d54964

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
